status = error
name = PropertiesConfig

# Console appender
appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{ISO8601}] [%p] %c{1.} - %m%n

# Root logger
rootLogger.level = off
rootLogger.appenderRef.console.ref = console

# Specific logger levels
logger.org_elasticsearch.name = org.elasticsearch
logger.org_elasticsearch.level = off
logger.org_elasticsearch.appenderRef.console.ref = console

logger.org_apache_http.name = org.apache.http
logger.org_apache_http.level = off
logger.org_apache_http.appenderRef.console.ref = console

logger.org_apache_lucene.name = org.apache.lucene
logger.org_apache_lucene.level = off
logger.org_apache_lucene.appenderRef.console.ref = console

logger.deprecation.name = org.elasticsearch.deprecation
logger.deprecation.level = off
logger.deprecation.appenderRef.console.ref = console
